
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry-operator-system
spec:
  mode: deployment
  #mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:

    exporters:
      #logging:
      otlp:
        # change the endpoint according to the chronocollector tracing svc
        endpoint: "otel-auto-inst-chronocollector-tracing:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]